# Generated by Django 6.0.4 on 2026-05-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rendezvous_lecon_userprofile_rendezvous_apprenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heuresformation',
            options={'verbose_name': 'Heures de formations', 'verbose_name_plural': 'Heures de formations'},
        ),
        migrations.AlterModelOptions(
            name='lecon',
            options={'verbose_name': 'Leçon', 'verbose_name_plural': 'Leçons'},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
    ]
