# Generated by Django 6.1 on 2026-09-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_quizquestion_alter_heuresformation_solde_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizChoice',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
