# Generated by Django 6.0.4 on 2026-05-11 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('WAIT', 'En attente'), ('OK', 'Confirmé'), ('DEL', 'Annulé')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField()),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.rendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('apprenant', 'Apprenant'), ('moniteur', 'Moniteur'), ('secretaire', 'Secrétaire'), ('admin', 'Admin')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rdv_apprenant', to='polls.userprofile'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='moniteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rdv_moniteur', to='polls.userprofile'),
        ),
        migrations.CreateModel(
            name='HeuresFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.IntegerField()),
                ('apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
