# Generated by Django 6.0.5 on 2026-05-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_heuresformation_options_alter_lecon_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Întrebare')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('explanation', models.TextField(verbose_name='Explicație AI')),
                ('difficulty', models.CharField(choices=[('EASY', 'Facile'), ('MEDIUM', 'Moyen'), ('HARD', 'Difficile')], default='MEDIUM', max_length=10)),
            ],
            options={
                'verbose_name': 'Întrebare Quiz',
                'verbose_name_plural': 'Întrebări Quiz',
            },
        ),
        migrations.AlterField(
            model_name='heuresformation',
            name='solde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('apprenant', 'Apprenant'), ('moniteur', 'Moniteur'), ('secretaire', 'Secrétaire'), ('admin', 'Admin')], default='apprenant', max_length=20),
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.quizquestion')),
            ],
        ),
    ]
